### ISSUE TITLE
Translate to English 

### ISSUE THREAD

**Issue by ggarnier** [rootsongjc/istio-handbook#1]
Any plans to translate this handbook to english?

**Comment by rootsongjc** [comment]
This book is just beginning to be written, it was written in Chinese at first. I want to be able to write together in the community. Of course, the English version can also be issued at the same time.

**Comment by rootsongjc** [comment]
@ggarnier This repo has been moved to https://github.com/servicemesher/istio-handbook, and we have a [slack workspace](https://servicemesher.slack.com), you can choose whether to join it or not.
